language: node_js
cache: yarn
node_js:
- node

script:
- yarn build

branches:
  only:
    - website

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  local-dir: dist/
  on:
    branch: website

env:
  global:
    secure: sWVJoy5tuFOgazzwpj1h4st9Te8gqL9HkIAdZmutLcohWHYRX6rmhXI3g2qJbwgfUIW5ukDX1V/QTljo0eAD9iavTGMyi0zMuU770W3p1qAjMrDc+p9Y4RuBJqOsducYys0H9u97iguj45EwgzuF4kE2XicFMQD0i0YSgrbpJA+Cu2gDKM6xhbZjtdCdZr8WxGRXyPBYOyJKp3gutDj9kRtDE2L3PRATV4b8jJB1C4hS9jRBXWoxW9CVr3HccE6wReu0/4MMsgXOQBu89Y/Wa78IyvUyO9Rbu9LX1MFbeNnYT2ROq3XLrZ5v7EFhnozuxlhjcDZZuc1NGk1QLKhQipjWjZyzmRYGWkOF8AF4EJhn2MdEb8moOioZaxf1FosLmF2+jb8chowEGM//YaQ+VyGmaAb01NaUKItgzBErwJgU4gSMQcPhts+Ge7Ui3DIVgx0IS/XkNvwP/H9GF6vxf9xQ6rOxehWUcdL04I4ooIMucJUGl9w8yNsTkENZFGVz6ir4ydgrYifhZ2MNbo+MrIGKhoqJwpQXmkkNm8Cl2AVVSOCPc/zrsdU35T+16HJ/aWscgBJvJCi/0PlakDt80/TpYx3dkJ/otIlDffYfcswRFugDyGaPCZ33OSADmJcnfSqoqKAMhikE//0FYtXg5TOpXxYFB0v0D+PyWj243yg=
