env:
  global:
  - secure: ZJX/nNNQGR6RdYPPqXpN0+IVv6QSGqW7sIa5JkVr7ZkWzbwkkwdHMCJwiqNb2TnNC67cci7GM4a8FGHtvlb62BxngnF3doEL+obNsZ15RS5atsmR9U5WIjStMMsd1SLzUFUyj7tlVaCcOGMatS8fuK9N2EfvKiMO6pSiS0AaTEQEsPzwyH9vzgKMaxOTg1iQRyWGWZxATmAW1m0Y/ZOTz9qIkaUYIfVLfAuVqF1dW0iEAKpt6HX0tUz353xx1GAh/dtLmpFojtK666hGyIazyZfYJClLHyqun9KAj7bZJTIQ76eyhnLyqDkvifooAE9bwJCk4sowGiYSsDxda9f8go7YOOSBQQK4yp+ABKtnd4nP5WhyWcabLAWBrTSRRMBgg//5Mk8ObiS7oUe9VfFSojrsMIkOhyGq6WWnY/gRxcEJqzxGf3ZGdFrEJKIf+7rfClb+icgdDgaaNd+VCHTBWdebF+Vxv+KxuUGBU81NDMnLiYpJgsY4BOYnzdioIbApRe6M/Eo6+Zb54K/NN1nWpa0uYsh2chKLS5RBLYZzD1pvQN4bifiU8MGXJ413nqWOTKIuUyS7XVtqitntnkMdc1pNhtCTHFdDfxKpnt6mATeAhh2VSDSzRpB0n3xvM1Oyi9y3ucz4dmiaUCW2jsr8700opwl6fY+hp6lIOZKkQj8=
language: node_js
cache: yarn
node_js:
- node
script:
- yarn upgrade ebnf2railroad
- yarn build
branches:
  only:
  - website
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  on:
    branch: website
